module_vote = "Votes"

txt_vote_count = "Votes: %s"
txt_vote_score = "Score: %.01f"


########
# Vote #
########
msg_vote_voted = "Your vote for %s has been registered. %d votes with %.01f Stars of %d"
